ALTER TABLE users ADD COLUMN phone VARCHAR(30);
ALTER TABLE users ADD COLUMN course_name VARCHAR(120);
ALTER TABLE users ADD COLUMN photo_url VARCHAR(300);
ALTER TABLE users ADD COLUMN email_verified BOOLEAN NOT NULL DEFAULT 0;
