TEMPLATE_CATALOG = [
    (
        "ats-standard",
        "ATS Standard",
        "ATS",
        "single-column",
        "optimized",
        False,
        101,
        ["All roles", "Online applications", "Strict ATS portals"],
        "Strict one-column ATS layout with standard headings, real text, and no visual parsing risks.",
        ["ATS", "Plain text", "Single column"],
    ),
    (
        "steady-form",
        "Precision ATS",
        "ATS",
        "single-column",
        "high",
        False,
        100,
        ["Data Analysts", "Engineers", "Technical Roles"],
        "A compact single-column layout optimized for fast ATS parsing and precise alignment.",
        ["Monochrome", "ATS"],
    ),
    (
        "classic-serif",
        "Heritage Serif",
        "Professional",
        "single-column",
        "optimized",
        False,
        99,
        ["Consultants", "Business", "General Professional"],
        "A timeless black-and-white serif resume with formal rules and generous readability.",
        ["Serif", "Black & White"],
    ),
    (
        "mercury-flow",
        "Modern Halo",
        "Modern",
        "single-column",
        "high",
        False,
        98,
        ["Sales", "Customer Success", "Product Roles"],
        "A contemporary single-column resume with a soft header and balanced visual rhythm.",
        ["Soft Gray", "Modern"],
    ),
    (
        "slate-dawn",
        "Executive Slate",
        "Executive",
        "two-column",
        "high",
        False,
        97,
        ["Leadership", "Management", "Communications"],
        "A distinctive two-column executive resume with a slate banner and editorial hierarchy.",
        ["Slate", "Serif"],
    ),
    (
        "minimalist-line", "Minimalist Line", "Minimal", "single-column", "high", False, 96,
        ["Early Career", "Technical Roles", "General Professional"],
        "A clean, restrained single-column layout with left-aligned hierarchy and generous whitespace.",
        ["Minimal", "Clean"],
    ),
    (
        "sidebar-focus", "Sidebar Focus", "Modern", "two-column", "high", False, 95,
        ["Product", "Design", "Customer Success"],
        "A practical two-column layout that gives skills and contact details a focused sidebar.",
        ["Sidebar", "Teal"],
    ),
    (
        "compact-impact", "Compact Impact", "ATS", "single-column", "optimized", False, 94,
        ["Consultants", "Analysts", "One-page Resumes"],
        "A dense, highly scannable one-page style for concise accomplishment-led resumes.",
        ["Compact", "ATS"],
    ),
    (
        "studio-bold", "Studio Bold", "Creative", "single-column", "high", False, 93,
        ["Marketing", "Creative", "Brand Roles"],
        "A bold, left-aligned header treatment for creative and marketing professionals.",
        ["Bold", "Creative"],
    ),
    (
        "timeline-teal", "Timeline Teal", "Modern", "two-column", "high", False, 92,
        ["Product Managers", "Operations", "Customer Success"],
        "A calm teal sidebar paired with a clear accomplishment timeline.",
        ["Timeline", "Teal"],
    ),
    ("sidebar-mono", "Sidebar Mono", "Minimal", "two-column", "high", False, 91, ["Developers", "Analysts", "Early Career"], "A crisp monochrome sidebar with restrained editorial spacing.", ["Monochrome", "Sidebar"]),
    ("horizon-coral", "Horizon Coral", "Creative", "single-column", "high", False, 90, ["Marketing", "Design", "Communications"], "A warm color-block header with a spacious single-column reading flow.", ["Coral", "Editorial"]),
    ("ledger-navy", "Ledger Navy", "Professional", "single-column", "very-high", False, 89, ["Finance", "Consulting", "Business"], "A precise navy ledger with compact dividers and focused hierarchy.", ["Navy", "Structured"]),
    ("split-olive", "Split Olive", "Modern", "two-column", "high", False, 88, ["Sustainability", "Operations", "Research"], "An earthy split layout that separates evidence from credentials.", ["Olive", "Split"]),
    ("canvas-sand", "Canvas Sand", "Minimal", "single-column", "high", False, 87, ["General Professional", "Education", "Nonprofit"], "A soft sand header with understated, highly readable sections.", ["Sand", "Minimal"]),
    ("column-indigo", "Column Indigo", "Executive", "two-column", "high", False, 86, ["Leadership", "Product", "Strategy"], "A confident indigo sidebar for leadership stories and core strengths.", ["Indigo", "Column"]),
    ("arc-slate", "Arc Slate", "ATS", "single-column", "very-high", False, 85, ["Engineering", "Analytics", "Technical Roles"], "A slate-gray ATS layout with clean rules and compact evidence blocks.", ["Slate", "ATS"]),
    ("pulse-rose", "Pulse Rose", "Creative", "two-column", "high", False, 84, ["Brand", "Marketing", "People Operations"], "A rose-accented two-column composition with an energetic but professional rhythm.", ["Rose", "Contemporary"]),
    ("signal-amber", "Signal Amber", "Modern", "single-column", "high", False, 83, ["Sales", "Growth", "Customer Success"], "A bold amber title band that keeps the resume content calm and scannable.", ["Amber", "Bold"]),
    ("navy-portrait", "Navy Portrait", "Professional", "single-column", "high", True, 82, ["Analysts", "Engineers", "Business Professionals"], "A navy portrait header with structured timeline entries and centered section bars.", ["Navy", "Photo", "Structured"]),
]

LEGACY_TEMPLATE_ALIASES = {
    "ats": "steady-form",
    "ats-classic": "steady-form",
    "ats-prime": "steady-form",
    "clearpath": "steady-form",
    "essential-one": "steady-form",
    "simple-standard": "steady-form",
    "precision-line": "steady-form",
    "clean-career": "steady-form",
    "graduate-launch": "steady-form",
    "first-career": "steady-form",
    "engineering-core": "steady-form",
    "academic-scholar": "classic-serif",
    "research-profile": "classic-serif",
    "classic": "classic-serif",
    "traditional-professional": "classic-serif",
    "classic-clear": "mercury-flow",
    "professional-edge": "mercury-flow",
    "executive-center": "mercury-flow",
    "professional-teal": "mercury-flow",
    "business-profile": "mercury-flow",
    "consulting-standard": "mercury-flow",
    "finance-formal": "mercury-flow",
    "modern": "mercury-flow",
    "urban-teal": "mercury-flow",
    "contemporary-grid": "mercury-flow",
    "creative-accent": "mercury-flow",
    "photo-signature": "mercury-flow",
    "leadership-profile": "slate-dawn",
    "executive-line": "slate-dawn",
    "executive-sidebar": "slate-dawn",
    "senior-impact": "slate-dawn",
    "two-page-pro": "slate-dawn",
    "modern-slate": "slate-dawn",
    "horizon-blue": "slate-dawn",
    "designer-portfolio": "slate-dawn",
    "modern-sidebar": "slate-dawn",
    "modern-sidebar-pro": "slate-dawn",
    "cobalt-line": "slate-dawn",
    "corporate-blue": "slate-dawn",
    "analyst-pro": "steady-form",
    "data-analyst-pro": "steady-form",
    "tech-horizon": "steady-form",
    "product-builder": "steady-form",
    "compact-metrics": "steady-form",
    "datacraft": "steady-form",
    "ai-specialist": "steady-form",
    "compact": "classic-serif",
    "compact-career": "classic-serif",
    "minimal-focus": "classic-serif",
    "default": "steady-form",
}


def template_metadata(template):
    (
        template_id,
        name,
        category,
        layout,
        ats_level,
        supports_photo,
        popularity,
        recommended_for,
        description,
        themes,
    ) = template
    return {
        "id": template_id,
        "name": name,
        "category": category,
        "layout": layout,
        "ats_level": ats_level,
        "supports_photo": supports_photo,
        "popularity": popularity,
        "recommended_for": recommended_for,
        "description": description,
        "themes": themes,
    }


TEMPLATE_METADATA = [template_metadata(template) for template in TEMPLATE_CATALOG]
TEMPLATE_BY_ID = {template["id"]: template for template in TEMPLATE_METADATA}
VALID_TEMPLATE_IDS = set(TEMPLATE_BY_ID)
