import json
import random
import secrets
import time
import uuid
from flask import current_app
from .ai_service import AIProviderError, empty_usage, json_completion, merge_usage
ProviderError = AIProviderError
from .question_validation import content_hash, structural_hash, validate_generated_item, questions_are_near_duplicates, INTERNAL_TOKEN_PATTERN
from ..utils.security import clean_text
from ..utils.explanation import normalize_explanation
from ..utils.code_formatting import apply_structured_code_fields, canonicalize_unlabelled_fences, normalize_fenced_text, validate_fenced_code
from ..topic_config import (
    CATEGORY_TOPIC_CONFIG,select_rotating_topic_names,
    select_weighted_topic_names,topic_definitions_for,
)

CATEGORIES={
    category:tuple(item["name"] for item in topic_definitions_for(category))
    for category in CATEGORY_TOPIC_CONFIG
}
DISTRIBUTION = [5,4,3,3,3,3]
DIFFICULTIES = ["Easy"]*6 + ["Medium"]*10 + ["Hard"]*4
CATEGORY_LEVELS={"Beginner":"Easy","Intermediate":"Medium","Advanced":"Hard"}
CATEGORY_PRACTICE_QUESTION_COUNT=10
TECHNICAL_LANGUAGES=("C","Java","Python","SQL")
DEFAULT_TECHNICAL_LANGUAGE="Python"

RETRY_VARIATION_DIRECTIONS = (
    "Use a different real-world setting, different entities, and a different question structure.",
    "Test a different facet of the assigned topic and use a new scenario with different relationships.",
    "Use a different representation or reasoning path; for numeric questions also use a different numeric range.",
)


def _normalized_exclusions(questions):
    """Build the single exclusion set shared by the prompt and validator."""
    normalized=[]
    seen=set()
    for question in questions or []:
        value=clean_text(question,360)
        key=value.casefold()
        if value and key not in seen:
            normalized.append(value)
            seen.add(key)
    return normalized


def _candidate_question_texts(items):
    questions=[]
    for item in items if isinstance(items,list) else []:
        if not isinstance(item,dict):
            continue
        question=clean_text(item.get("question"),360)
        if question and question.casefold() not in {row.casefold() for row in questions}:
            questions.append(question)
    return questions


def _extract_question_items(payload,expected_count):
    """Canonicalize common JSON wrappers without relaxing item validation.

    Groq JSON mode guarantees a JSON object, but it does not guarantee the
    application-level wrapper. In particular, a one-question request may be
    returned as ``{"question": {...}}``, ``{"questions": {...}}``, or as
    the question object itself. Accept those singleton shapes and let the
    existing strict question validator remain authoritative.
    """
    if not isinstance(payload,dict):
        return [],"non_object"
    questions=payload.get("questions")
    if isinstance(questions,list):
        return questions,"questions_array"
    if expected_count==1:
        if isinstance(questions,dict):
            return [questions],"questions_object"
        question=payload.get("question")
        if isinstance(question,dict):
            return [question],"question_object"
        required={"question","options","correct_answer","explanation","category","topic","difficulty"}
        if required.issubset(payload):
            return [payload],"bare_question_object"
    return [],"unsupported_wrapper"


def _retry_context(base_prompt,error,rejected_questions,attempt):
    direction=RETRY_VARIATION_DIRECTIONS[(attempt-1)%len(RETRY_VARIATION_DIRECTIONS)]
    retry_seed=f"{secrets.randbelow(900000)+100000}-{str(uuid.uuid4())[:8]}"
    return f"""{base_prompt}

RETRY CORRECTION {attempt}:
- The previous response was rejected because: {clean_text(str(error),240)}.
- Questions generated by all rejected attempts so far are listed below. Do not reuse their concept, scenario, structure, wording, entities, or numbers:
{json.dumps(rejected_questions,ensure_ascii=False)}
- Required variation: {direction}
- Fresh private retry seed: {retry_seed}. Use it only to force a materially different result; never include it in the response.
Regenerate the complete JSON response and correct the validation failure."""


def _topic_sequence(topics,count,rng):
    """Return a shuffled topic sequence, repeating only when unavoidable."""
    available=list(dict.fromkeys(topics))
    if not available:raise ValueError("Choose at least one aptitude topic")
    if len(available)>=count:return rng.sample(available,count)
    selected=[]
    while len(selected)<count:
        cycle=list(available);rng.shuffle(cycle)
        if len(cycle)>1 and selected and cycle[0]==selected[-1]:
            cycle[0],cycle[1]=cycle[1],cycle[0]
        selected.extend(cycle)
    return selected[:count]


def _topic_rng(seed=None):
    # SystemRandom varies standalone calls. A test-id seed lets the live
    # question flow reconstruct one stable schedule throughout an attempt.
    return random.SystemRandom() if seed is None else random.Random(str(seed))


def _slot(category,topic,difficulty,technical_language=None):
    row={"category":category,"topic":topic,"difficulty":difficulty}
    if category=="Technical Aptitude":
        row["technical_language"]=technical_language or DEFAULT_TECHNICAL_LANGUAGE
    return row


def build_slots(category=None,seed=None,category_counts=None,technical_language=None,topics_by_category=None):
    rng=_topic_rng(seed)
    if category:
        difficulties=["Easy","Easy","Medium","Medium","Hard"]
        selected=select_rotating_topic_names(topic_definitions_for(category),[],len(difficulties),rng)
        return [_slot(category,topic,difficulty,technical_language) for topic,difficulty in zip(selected,difficulties)]
    slots=[]
    configured_counts=(
        [int(category_counts.get(name,0)) for name in CATEGORIES]
        if category_counts is not None else DISTRIBUTION
    )
    if category_counts is not None and any(count < 3 or count > 10 for count in configured_counts):
        raise ValueError("Every Mixed Test category must have between 3 and 10 questions")
    for category,count in zip(CATEGORIES,configured_counts):
        supplied=(topics_by_category or {}).get(category)
        if supplied is not None:
            selected=list(supplied[:count])
            if len(selected)!=count or len({topic.casefold() for topic in selected})!=count:
                raise ValueError(f"Mixed Test topic schedule is invalid for {category}")
        else:
            selected=select_rotating_topic_names(topic_definitions_for(category),[],count,rng)
        for topic in selected:slots.append(_slot(category,topic,None,technical_language))
    slots.sort(key=lambda row:len(row["topic"])%7)
    for i,slot in enumerate(slots):slot["difficulty"]=DIFFICULTIES[i%len(DIFFICULTIES)]
    return slots


def build_category_slots(category,level,topics=None,seed=None,technical_language=None):
    if category not in CATEGORIES:raise ValueError("Choose a valid aptitude category")
    if level not in CATEGORY_LEVELS:raise ValueError("Choose Beginner, Intermediate or Advanced")
    # Explicit topics are already a history-aware attempt schedule selected by
    # topic_selection_service, so preserve their order. Direct callers receive
    # a newly shuffled schedule rather than the former fixed modulo walk.
    topics=(list(topics) if topics is not None else select_weighted_topic_names(
        topic_definitions_for(category),[],CATEGORY_PRACTICE_QUESTION_COUNT,_topic_rng(seed),
    ))
    if not topics:raise ValueError("Choose at least one Category Practice topic")
    difficulty=CATEGORY_LEVELS[level]
    return [_slot(category,topics[index%len(topics)],difficulty,technical_language) for index in range(CATEGORY_PRACTICE_QUESTION_COUNT)]


def _minimal_safe_item(item,slot,internal_values=()):
    """Return a structurally safe last candidate for a deadline fallback.

    Full validation remains authoritative. This deliberately narrow fallback
    is used only after the learner-facing deadline expires and still rejects
    malformed options, metadata leaks, and slot mismatches.
    """
    selected_language=str(slot.get("technical_language") or "python").lower()
    try:item=apply_structured_code_fields(item,slot["category"],selected_language)
    except ValueError:return None
    required={"question","options","correct_answer","explanation","category","topic","difficulty"}
    if not isinstance(item,dict) or not required.issubset(item):return None
    options=item.get("options")
    if not isinstance(options,dict) or set(options)!={"A","B","C","D"}:return None
    technical=slot["category"]=="Technical Aptitude"
    options={key:(normalize_fenced_text(canonicalize_unlabelled_fences(value,selected_language),500) if technical else clean_text(value,500)) for key,value in options.items()}
    answer=clean_text(item.get("correct_answer"),1).upper()
    question=normalize_fenced_text(canonicalize_unlabelled_fences(item.get("question"),selected_language),2000) if technical else clean_text(item.get("question"),2000)
    explanation=(normalize_fenced_text(canonicalize_unlabelled_fences(item.get("explanation"),selected_language),3000,normalize_explanation) if technical else normalize_explanation(item.get("explanation"),3000))
    if technical:
        try:
            for value in (question,*options.values(),explanation):validate_fenced_code(value,selected_language)
        except ValueError:
            return None
    if answer not in options or any(not value for value in options.values()):return None
    if len({value.casefold() for value in options.values()})!=4 or len(question)<12 or len(explanation)<10:return None
    if clean_text(item.get("category"),80)!=slot["category"]:return None
    if clean_text(item.get("topic"),100).casefold()!=slot["topic"].casefold():return None
    if clean_text(item.get("difficulty"),10).casefold()!=slot["difficulty"].casefold():return None
    public_text="\n".join((question,*options.values(),explanation))
    if INTERNAL_TOKEN_PATTERN.search(public_text):return None
    if any(str(value).strip().casefold() in public_text.casefold() for value in internal_values if len(str(value).strip())>=4):return None
    return {**slot,"question":question,"options":options,"correct_answer":answer,"explanation":explanation,"content_hash":content_hash(question),"structural_hash":structural_hash(question,slot["category"],slot["topic"])}


def generate_questions(slots, avoid_questions=None, avoid_number_patterns=None, allow_demo_fallback=True, *, deadline=None, max_validation_attempts=3, background=False):
    total_started=time.perf_counter()
    if not current_app.config.get("OPENAI_API_KEY"):
        if allow_demo_fallback and current_app.config["ALLOW_DEMO_QUESTIONS"]: return demo_questions(slots,avoid_questions), "demo-fixture", empty_usage()
        raise RuntimeError("OpenAI question generation is unavailable")
    prompt_slots=[{**slot,"variation_seed":secrets.randbelow(900000)+100000,"scenario_seed":str(uuid.uuid4())[:8]} for slot in slots]
    batch_id=str(uuid.uuid4())
    # Normalize once, then use this exact full set in both the prompt and the
    # near-duplicate validator. This prevents the model from colliding with a
    # question that validation checks but generation was never told about.
    forbidden_questions=_normalized_exclusions(avoid_questions)
    recent_count=len(forbidden_questions)
    blocked_patterns=(avoid_number_patterns or [])[:24]
    technical_code_example=json.dumps({
        "question_code":{"language":"python","code":"def add(a, b):\n    return a + b"},
        "explanation_code":{"language":"python","code":"print(add(1, 2))"},
        "option_code":{"A":{"language":"python","code":"return a + b"}},
    },ensure_ascii=False)
    prompt = f"""Return one top-level JSON object whose questions field is always an array: {{"questions":[QUESTION_OBJECT]}}. Return exactly one original four-option MCQ per slot. Even when there is only one slot, never return a bare question object, a singular "question" field, or an object directly inside "questions".
Preserve every slot's category, topic, and difficulty exactly and omit the seed fields. Each question must contain: question, options A-D, correct_answer letter, explanation, category, topic, difficulty. Return valid JSON only; no HTML or Markdown.
The variation_seed, scenario_seed, and Batch ID are private prompt metadata. Never mention, reference, copy, or include their names OR VALUES anywhere in question text, options, or explanations.

Originality rules:
- Generate fresh, varied numeric values for every question.
- Avoid commonly reused textbook patterns such as 180/195/210 and a 15 percent discount on 800 currency units.
- No two questions in this response may share the same complete set of numeric values, even when their scenario wording differs.
- Avoid reusing these recent typed number patterns: {json.dumps(blocked_patterns)}.
- Do not repeat, paraphrase, test the same answer concept, or use a close variation of any question in this learner's recent-question list below. Choose a different topic, scenario, and skill angle when possible.
- Recent questions to avoid (reference only; never reproduce them): {json.dumps(forbidden_questions, ensure_ascii=False)}.

Explanation quality rules:
- For non-math questions, write 2-4 concise sentences and no more than 400 characters.
- For quantitative questions, output only a short numbered calculation. Inside the JSON explanation string, separate every step with the literal JSON newline escape \\n. Use exactly: "Step 1: [first calculation].\\nStep 2: [finish calculation and explicitly produce the selected option value].\\nStep 3: Answer = [copy the complete selected option text exactly]." Never combine multiple Step markers into one paragraph. Example: if the selected option text is "18", Step 2 must calculate and end in 18, and the final line must be exactly "Step 3: Answer = 18." A final calculation may instead appear immediately before "Answer = 18" in the same last step. Never end with only an option letter, an unsupported result, or a different final format.
- Write numeric expressions clearly, for example "180 + 195 + 210 = 585", rather than embedding calculations in dense prose.
- Work out each problem once internally. Do not think out loud, recalculate the same values, second-guess the result, or include contradictory reasoning.
- The explanation's final answer/value must exactly match the option selected by correct_answer. Double-check that consistency before responding.
- The final answer/value must first appear as the result of an earlier calculation or reasoning step. Never introduce an unsupported value only in the final Answer step.
- Solve the problem before composing its options. Exactly one option must be valid. Never select a merely "closest" option; if the solved value is absent, fix the options internally before returning JSON.

Technical Aptitude code-format rules:
- Technical Aptitude slots include technical_language. For code-output, syntax, debugging, or implementation questions, use exactly that selected language and never substitute another language. Conceptual questions such as OOP principles, algorithms, flowcharts, or pseudocode may remain language-neutral.
- C means ISO C syntax, Java means Java syntax, Python means Python syntax, and SQL means standard SQL query syntax. Match every structured code object's language field to the selected technical_language using lowercase values c, java, python, or sql.
- Never place Markdown fences inside the JSON response. Put normal prose in question/explanation and program code in optional structured objects instead.
- Do not type triple-backtick Markdown anywhere in question, explanation, options, or any code value. A code object's code field contains raw source code only; the application formats it for display.
- Use this structural example (omit fields that are not needed): {technical_code_example}.
- Preserve indentation and line breaks inside every code value using valid JSON newline escapes. Never compress a multi-line program into one line.
- Omit these optional code objects for conceptual Technical Aptitude questions containing no code. Do not return empty code objects.

This learner has already seen {recent_count} questions. Use every slot's variation_seed and scenario_seed to create materially different wording, numeric values, names, and contexts. Even conceptual questions must use a fresh applied scenario rather than a standard textbook question.
Batch ID: {batch_id}
Slots: {json.dumps(prompt_slots)}"""
    current_app.logger.info(
        "Live generation timing step=prompt_build duration_ms=%.2f slots=%s prompt_chars=%s recent_exclusions=%s",
        (time.perf_counter()-total_started)*1000,len(slots),len(prompt),len(forbidden_questions),
    )
    last_error=None
    accumulated_usage=empty_usage()
    retry_prompt=prompt
    rejected_questions=[]
    max_validation_attempts=max(1,int(max_validation_attempts))
    last_minimal=None;last_model=None
    for attempt in range(1,max_validation_attempts+1):
        if deadline is not None and time.monotonic()>=deadline:
            if last_minimal:
                current_app.logger.warning("Live generation deadline reached; using minimally-safe candidate before attempt=%s",attempt)
                accumulated_usage["validation_attempt_count"]=max(1,attempt-1)
                return [last_minimal],last_model or current_app.config["OPENAI_MODEL"],accumulated_usage
            raise TimeoutError("live question generation deadline exceeded")
        attempt_started=time.perf_counter()
        candidate_questions=[]
        try:
            current_app.logger.info(
                "OpenAI question-generation attempt=%s/%s slots=%s categories=%s recent_exclusions=%s",
                attempt,max_validation_attempts,len(slots),sorted({slot["category"] for slot in slots}),
                len(forbidden_questions),
            )
            groq_started=time.perf_counter()
            result=json_completion(
                "You are a rigorous aptitude assessment author. Solve privately, return only concise verified JSON, and never expose prompt metadata, internal field names, seeds, or their values.",
                retry_prompt,0.35,deadline=deadline,
                timeout=current_app.config.get("OPENAI_BACKGROUND_TIMEOUT_SECONDS",20) if background else current_app.config.get("OPENAI_TIMEOUT_SECONDS",6),
                maximum_tokens=current_app.config.get("QUESTION_GENERATION_MAX_COMPLETION_TOKENS",1536),
            )
            current_app.logger.info(
                "Live generation timing step=openai_call attempt=%s duration_ms=%.2f",
                attempt,(time.perf_counter()-groq_started)*1000,
            )
            if result is None: raise ValueError("OpenAI is unavailable")
            payload,usage=result
            accumulated_usage=merge_usage(accumulated_usage,usage)
            last_model=usage.get("model") or last_model
            items,response_shape=_extract_question_items(payload,len(slots))
            current_app.logger.info(
                "Live generation response shape attempt=%s shape=%s payload_keys=%s questions_count=%s expected_count=%s",
                attempt,response_shape,sorted(str(key) for key in payload),len(items),len(slots),
            )
            candidate_questions=_candidate_question_texts(items)
            if len(items)==len(slots):
                minimal=[_minimal_safe_item(item,slot,(prompt_slot["variation_seed"],prompt_slot["scenario_seed"],batch_id)) for item,slot,prompt_slot in zip(items,slots,prompt_slots)]
                if all(minimal) and not any(questions_are_near_duplicates(item["question"],seen) for item in minimal for seen in forbidden_questions):
                    # Learner live fallback only requests one slot. Keep the
                    # complete candidate available if a later full-quality
                    # validation retry runs out of the shared deadline.
                    if len(minimal)==1:last_minimal=minimal[0]
            if len(items)!=len(slots): raise ValueError(f"expected {len(slots)} questions")
            validation_started=time.perf_counter()
            validated=[
                validate_generated_item(
                    # category/topic/difficulty (and technical_language) are
                    # already known server-side from `slot` — the model is
                    # asked to echo them back, but that's an unforced,
                    # sometimes-dropped field rather than real content, so
                    # `slot` always wins on overlap instead of failing
                    # validation when the model omits or restates them.
                    # Matches the same precedent already used by
                    # `_minimal_safe_item` above.
                    {**item,**slot},slot,
                    internal_values=(prompt_slot["variation_seed"],prompt_slot["scenario_seed"],batch_id),
                )
                for item,slot,prompt_slot in zip(items,slots,prompt_slots)
            ]
            content_hashes=[item["content_hash"] for item in validated]
            structural_hashes=[item["structural_hash"] for item in validated if item["structural_hash"]]
            if len(content_hashes)!=len(set(content_hashes)):raise ValueError("response contains duplicate question wording")
            if len(structural_hashes)!=len(set(structural_hashes)):raise ValueError("response contains structurally duplicate numeric questions")
            if any(questions_are_near_duplicates(item["question"],seen) for item in validated for seen in forbidden_questions):
                raise ValueError("response repeats a recent or in-test question concept")
            current_app.logger.info(
                "Live generation timing step=parse_validate attempt=%s duration_ms=%.2f items=%s",
                attempt,(time.perf_counter()-validation_started)*1000,len(validated),
            )
            current_app.logger.info(
                "Live generation timing step=total duration_ms=%.2f successful_attempt=%s",
                (time.perf_counter()-total_started)*1000,attempt,
            )
            accepted_model=usage.get("model") or current_app.config["OPENAI_MODEL"]
            accumulated_usage["validation_attempt_count"]=attempt
            return validated,accepted_model,accumulated_usage
        except ProviderError as exc:
            # A provider outage or quota response cannot be fixed by asking
            # for another wording variation. Preserve it for the route so the
            # learner receives the real retryable reason.
            if exc.kind=="deadline_exceeded" and last_minimal:
                current_app.logger.warning("Live generation provider deadline reached; using minimally-safe candidate")
                accumulated_usage["validation_attempt_count"]=attempt
                return [last_minimal],last_model or current_app.config["OPENAI_MODEL"],accumulated_usage
            if allow_demo_fallback and current_app.config["ALLOW_DEMO_QUESTIONS"]:
                current_app.logger.warning(
                    "OpenAI provider unavailable; using local development fixture kind=%s status_code=%s error=%s",
                    exc.kind,exc.status_code,str(exc)[:240],
                )
                accumulated_usage["validation_attempt_count"]=attempt
                return demo_questions(slots,avoid_questions),"demo-fixture-provider-fallback",accumulated_usage
            raise
        except Exception as exc:
            last_error=exc
            for question in candidate_questions:
                if question.casefold() not in {row.casefold() for row in rejected_questions}:
                    rejected_questions.append(question)
            current_app.logger.info(
                "Live generation timing step=failed_attempt attempt=%s duration_ms=%.2f error_type=%s",
                attempt,(time.perf_counter()-attempt_started)*1000,type(exc).__name__,
            )
            current_app.logger.warning("OpenAI question validation attempt %s/%s failed: %s",attempt,max_validation_attempts,str(exc)[:240])
            retry_prompt=_retry_context(prompt,exc,rejected_questions,attempt)
            if deadline is not None and time.monotonic()>=deadline and last_minimal:
                current_app.logger.warning("Live generation validation deadline reached; using minimally-safe candidate")
                accumulated_usage["validation_attempt_count"]=attempt
                return [last_minimal],last_model or current_app.config["OPENAI_MODEL"],accumulated_usage
    if allow_demo_fallback and current_app.config["ALLOW_DEMO_QUESTIONS"]:
        current_app.logger.error(
            "OpenAI question validation exhausted; using the local development fixture: %s",
            str(last_error)[:240],
        )
        return demo_questions(slots,avoid_questions), "demo-fixture-fallback", accumulated_usage
    raise ValueError(f"OpenAI output failed validation after {max_validation_attempts} attempts: {last_error}") from last_error


def demo_questions(slots, avoid_questions=None):
    templates=[
      ("A shop marks an item at ₹800 and offers a 15% discount. What is the selling price?",{"A":"₹640","B":"₹680","C":"₹700","D":"₹720"},"B","Step 1: 15% of ₹800 = ₹120. Step 2: ₹800 - ₹120 = ₹680. Step 3: Answer = ₹680."),
      ("Choose the next number: 3, 8, 15, 24, 35, ?",{"A":"46","B":"47","C":"48","D":"49"},"C","The differences are 5, 7, 9, 11 and then 13, giving 48."),
      ("Choose the word closest in meaning to meticulous.",{"A":"Careless","B":"Precise","C":"Rapid","D":"Ordinary"},"B","Meticulous means showing great attention to detail, so precise is closest."),
      ("All analysts are readers. Which conclusion is guaranteed?",{"A":"All writers are analysts","B":"Some analysts are writers","C":"All analysts are readers","D":"No readers are analysts"},"C","The conclusion repeats the fact directly established by the premise."),
      ("Which operating system component manages CPU scheduling and memory?",{"A":"Browser","B":"Kernel","C":"Compiler","D":"Spreadsheet"},"B","The kernel manages core resources including CPU scheduling and memory."),
      ("Which data structure follows First In, First Out?",{"A":"Stack","B":"Tree","C":"Queue","D":"Graph"},"C","A queue removes elements in the same order they are inserted: FIFO."),
    ]
    template_by_category=dict(zip(CATEGORIES,templates))
    variants={
      "Quantitative Aptitude":[
        templates[0],
        ("A class has 18 boys and 12 girls. What is the ratio of boys to girls in simplest form?",{"A":"2:3","B":"3:2","C":"3:5","D":"5:3"},"B","Step 1: The ratio is 18:12. Step 2: Divide both values by 6 to get 3:2. Step 3: Answer = 3:2."),
        ("A worker completes a task in 6 days. What fraction of the task is completed in one day?",{"A":"1/3","B":"1/5","C":"1/6","D":"1/12"},"C","Step 1: One whole task is completed in 6 days. Step 2: One day completes 1 divided by 6. Step 3: Answer = 1/6."),
        ("What is the average of 14, 18, and 22?",{"A":"16","B":"18","C":"20","D":"54"},"B","Step 1: 14 + 18 + 22 = 54. Step 2: 54 divided by 3 = 18. Step 3: Answer = 18."),
        ("A bag contains 3 red and 2 blue balls. What is the probability of drawing a blue ball?",{"A":"2/5","B":"3/5","C":"1/2","D":"1/3"},"A","Step 1: Total balls = 3 + 2 = 5. Step 2: Blue balls = 2. Step 3: Answer = 2/5."),
      ],
      "Logical Reasoning":[
        templates[1],
        ("If CAT is coded as DBU, how is DOG coded using the same rule?",{"A":"EPF","B":"CNE","C":"DPG","D":"EPH"},"D","Each letter is shifted forward by one: D becomes E, O becomes P, and G becomes H. The matching encoded word is EPH."),
        ("Ravi walks 4 km north and then 3 km east. In which direction is he from the starting point?",{"A":"North-west","B":"North-east","C":"South-east","D":"South-west"},"B","Moving north and then east places Ravi to the north-east of his starting point."),
        ("All poets are readers. Some readers are teachers. Which statement must be true?",{"A":"All teachers are poets","B":"Some poets are teachers","C":"All poets are readers","D":"No reader is a teacher"},"C","The first statement directly guarantees that all poets are readers."),
        ("Find the next letter: B, E, H, K, ?",{"A":"L","B":"M","C":"N","D":"O"},"C","The sequence moves forward three letters each time: B, E, H, K, N."),
      ],
      "Verbal Ability":[
        templates[2],
        ("Choose the grammatically correct sentence.",{"A":"She have completed the work.","B":"She has completed the work.","C":"She completing the work.","D":"She had complete the work."},"B","With the singular subject 'She', the present perfect form is 'has completed'."),
        ("Choose the best word: The manager praised the team for its ____ effort.",{"A":"careless","B":"collective","C":"fragile","D":"silent"},"B","Collective means done by people acting together, which fits a team effort."),
        ("Which word is the opposite of scarce?",{"A":"Rare","B":"Limited","C":"Abundant","D":"Small"},"C","Abundant means available in large quantities, the opposite of scarce."),
        ("In the sentence 'Maya was reluctant to volunteer,' which word can replace reluctant without changing the meaning?",{"A":"Eager","B":"Unwilling","C":"Certain","D":"Cheerful"},"B","Reluctant means unwilling or hesitant to do something."),
      ],
      "Analytical Reasoning":[
        ("A report shows sales rising from 40 to 55 units. What is the increase?",{"A":"10","B":"15","C":"40","D":"95"},"B","The increase is found by subtracting 40 from 55, which gives 15."),
        ("If every project needs a plan and Project X is a project, what follows?",{"A":"Project X needs a plan","B":"Every plan is Project X","C":"Project X has no plan","D":"No projects need plans"},"A","Applying the stated rule to Project X shows that it needs a plan."),
        ("Which chart is most useful for comparing values across named categories?",{"A":"Bar chart","B":"Flowchart","C":"Map","D":"Timeline"},"A","A bar chart makes comparisons between named categories clear."),
        ("A process has steps A, B, and C, and B must occur after A. Which order is valid?",{"A":"B, A, C","B":"C, B, A","C":"A, B, C","D":"B, C, A"},"C","The only listed order that places A before B is A, B, C."),
        ("A pattern repeats circle, square, triangle. What comes after circle, square, triangle, circle?",{"A":"Circle","B":"Square","C":"Triangle","D":"Star"},"B","The three-shape pattern repeats, so after the next circle comes square."),
      ],
      "Computer Fundamentals":[
        templates[4],
        ("Which protocol automatically assigns IP addresses on a network?",{"A":"DNS","B":"DHCP","C":"HTTP","D":"FTP"},"B","DHCP automatically provides network configuration such as IP addresses."),
        ("What is the main purpose of a database index?",{"A":"Speed up data retrieval","B":"Encrypt every record","C":"Replace backups","D":"Format disks"},"A","A database index speeds up data retrieval by locating matching records more quickly."),
        ("Which component performs arithmetic and logical operations?",{"A":"ALU","B":"Monitor","C":"Router","D":"Keyboard"},"A","The arithmetic logic unit, or ALU, performs arithmetic and logical operations."),
        ("Which security practice uses a second verification step after a password?",{"A":"Defragmentation","B":"Two-factor authentication","C":"Caching","D":"Virtualization"},"B","Two-factor authentication requires another verification factor in addition to a password."),
      ],
      "Technical Aptitude":[templates[5],("Which structure uses Last In, First Out order?",{"A":"Queue","B":"Stack","C":"Array","D":"Graph"},"B","A stack removes the most recently added item first, which is LIFO."),("What does a compiler do?",{"A":"Translates source code","B":"Stores web pages","C":"Routes packets","D":"Draws charts"},"A","A compiler translates source code into another executable or lower-level form."),("Which loop is best when the number of repetitions is known?",{"A":"for loop","B":"recursive call","C":"switch statement","D":"exception block"},"A","A for loop is commonly used when the iteration count is known."),("What is the purpose of a function parameter?",{"A":"Pass input to a function","B":"Delete variables","C":"Restart a program","D":"Create a database"},"A","Parameters allow a caller to provide input values to a function.")],
    }
    result=[]
    blocked=list(avoid_questions or [])
    for i,slot in enumerate(slots):
        candidates=variants.get(slot["category"],[template_by_category.get(slot["category"],templates[i%len(templates)])])
        selected=next((candidate for candidate in candidates if not any(questions_are_near_duplicates(candidate[0],seen) for seen in blocked)),None)
        if not selected:
            raise ValueError(f"Local development fixture has no unique {slot['category']} question remaining; add approved bank questions")
        q,opts,answer,explanation=selected
        result.append(validate_generated_item({**slot,"question":q,"options":opts,"correct_answer":answer,"explanation":explanation},slot))
        blocked.append(q)
    return result
