"""Opt-in route integration tests against a disposable MySQL database.

Run with ``RUN_MYSQL_INTEGRATION_TESTS=1``.  The database name is generated by
this test, the portable ``schema.sql`` is applied to it, every application DB
operation is redirected to its own connection pool, and cleanup is registered
before schema creation starts.  The configured live database is only counted
before/after as a safety sentinel and is never selected for a write.
"""

import json
import os
import re
import unittest
from pathlib import Path
from uuid import uuid4
from unittest.mock import patch

import mysql.connector
from dotenv import load_dotenv
from mysql.connector import pooling


BACKEND_DIR = Path(__file__).resolve().parents[1]
load_dotenv(BACKEND_DIR / ".env")

import db  # noqa: E402  (environment is loaded before DB configuration)
from app import create_app  # noqa: E402
from runtime_state import dashboard_cache  # noqa: E402


MYSQL_TESTS_ENABLED = os.environ.get("RUN_MYSQL_INTEGRATION_TESTS") == "1"
SAFE_DB_NAME = re.compile(r"^[A-Za-z0-9_]+$")


def _admin_config():
    return {
        "host": os.environ.get("DB_HOST", "localhost"),
        "port": int(os.environ.get("DB_PORT", "3306")),
        "user": os.environ.get("DB_USER", "root"),
        "password": os.environ.get("DB_PASSWORD", ""),
    }


def _execute_schema(cursor, schema_text):
    """Execute a mysql-client style script, including DELIMITER sections."""
    delimiter = ";"
    statement_lines = []
    for line in schema_text.splitlines():
        stripped = line.strip()
        if stripped.upper().startswith("DELIMITER "):
            if statement_lines and "".join(statement_lines).strip():
                raise AssertionError("Unexpected SQL before a DELIMITER directive")
            delimiter = stripped.split(None, 1)[1]
            continue

        statement_lines.append(line + "\n")
        buffered = "".join(statement_lines).rstrip()
        if buffered.endswith(delimiter):
            statement = buffered[: -len(delimiter)].strip()
            statement_lines = []
            if statement:
                cursor.execute(statement)

    if "".join(statement_lines).strip():
        raise AssertionError("schema.sql ended with an incomplete SQL statement")


@unittest.skipUnless(
    MYSQL_TESTS_ENABLED,
    "set RUN_MYSQL_INTEGRATION_TESTS=1 to run disposable-MySQL tests",
)
class MySQLRouteIntegrationTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.live_database = os.environ.get("DB_NAME", "mock_interview_db")
        if not SAFE_DB_NAME.fullmatch(cls.live_database):
            raise AssertionError("Configured DB_NAME is not a safe MySQL identifier")

        cls.temp_database = f"mock_interview_test_{uuid4().hex[:12]}"
        if cls.temp_database == cls.live_database:
            raise AssertionError("Temporary and live database names must differ")

        cls.original_pool = db.pool
        cls.temp_pool = None
        cls.admin = mysql.connector.connect(**_admin_config(), autocommit=True)
        cls.live_count_before = cls._live_interview_count()
        cls.addClassCleanup(cls._cleanup_database)

        schema_text = (BACKEND_DIR / "schema.sql").read_text(encoding="utf-8")
        schema_text = schema_text.replace("mock_interview_db", cls.temp_database)
        with cls.admin.cursor() as cursor:
            _execute_schema(cursor, schema_text)

        cls.temp_pool = pooling.MySQLConnectionPool(
            pool_name=f"mitest_{uuid4().hex[:10]}",
            pool_size=5,
            pool_reset_session=True,
            database=cls.temp_database,
            **_admin_config(),
        )
        db.pool = cls.temp_pool

        db.query(
            """INSERT INTO students
                 (id, name, email, course_enrolled, target_role)
               VALUES (%s, %s, %s, %s, %s)""",
            (
                1,
                "Disposable Integration Student",
                "mysql-integration@example.test",
                "Mock Interview QA",
                "Backend Developer",
            ),
        )

        cls.app = create_app()
        cls.app.config.update(TESTING=True)
        cls.client = cls.app.test_client()
        dashboard_cache.invalidate(1)

    @classmethod
    def _live_interview_count(cls):
        with cls.admin.cursor() as cursor:
            cursor.execute(
                f"SELECT COUNT(*) FROM `{cls.live_database}`.interviews"
            )
            return int(cursor.fetchone()[0])

    @classmethod
    def _cleanup_database(cls):
        # Stop application access to the disposable pool before dropping it.
        db.pool = cls.original_pool
        cleanup_error = None
        live_count_after = cls.live_count_before
        try:
            if cls.admin.is_connected():
                with cls.admin.cursor() as cursor:
                    cursor.execute(f"DROP DATABASE IF EXISTS `{cls.temp_database}`")
                    cursor.execute(
                        "SELECT SCHEMA_NAME FROM information_schema.SCHEMATA "
                        "WHERE SCHEMA_NAME = %s",
                        (cls.temp_database,),
                    )
                    if cursor.fetchone() is not None:
                        cleanup_error = AssertionError(
                            "Disposable MySQL database still exists after cleanup"
                        )
                live_count_after = cls._live_interview_count()
                if live_count_after != cls.live_count_before:
                    cleanup_error = AssertionError(
                        "Live interview count changed during disposable-DB tests: "
                        f"{cls.live_count_before} -> {live_count_after}"
                    )
        finally:
            cls.admin.close()

        print(
            "MYSQL_INTEGRATION_SAFETY "
            f"temporary_database={cls.temp_database} removed=true "
            f"live_interviews_before={cls.live_count_before} "
            f"live_interviews_after={live_count_after}"
        )
        if cleanup_error:
            raise cleanup_error

    def test_schema_objects_and_full_route_lifecycle(self):
        # Applying schema.sql must create all portable object types, not merely
        # the tables used by the route flow.
        tables, _ = db.query("SHOW FULL TABLES WHERE Table_type = 'BASE TABLE'", fetch=True)
        views, _ = db.query("SHOW FULL TABLES WHERE Table_type = 'VIEW'", fetch=True)
        routines, _ = db.query(
            """SELECT ROUTINE_NAME, ROUTINE_TYPE
               FROM information_schema.ROUTINES
               WHERE ROUTINE_SCHEMA = %s""",
            (self.temp_database,),
            fetch=True,
        )
        events, _ = db.query(
            """SELECT EVENT_NAME
               FROM information_schema.EVENTS
               WHERE EVENT_SCHEMA = %s""",
            (self.temp_database,),
            fetch=True,
        )
        self.assertEqual(len(tables), 6)
        self.assertEqual(len(views), 1)
        self.assertEqual(
            {(row["ROUTINE_NAME"], row["ROUTINE_TYPE"]) for row in routines},
            {
                ("get_remaining_questions", "FUNCTION"),
                ("record_answered_question", "PROCEDURE"),
            },
        )
        self.assertEqual([row["EVENT_NAME"] for row in events], ["cleanup_old_daily_usage"])

        questions = [
            {"topic_area": "generators and iterators", "question": "What is a Python generator?"},
            {"topic_area": "collections", "question": "How does a list differ from a tuple?"},
            {"topic_area": "context managers", "question": "What does a context manager do?"},
            {"topic_area": "exceptions", "question": "Why are exceptions useful?"},
            {"topic_area": "comprehensions", "question": "What is dictionary comprehension?"},
        ]
        answer_evaluation = {
            "verdict": "correct",
            "reason": "The core concept is accurate and clearly stated.",
            "ideal_answer": "A concise correct explanation.",
            "follow_up_needed": False,
            "follow_up_question": None,
        }
        final_evaluation = {
            "overall_score": 8.4,
            "technical_accuracy": 8.6,
            "communication_clarity": 8.2,
            "confidence": 8.0,
            "strengths": json.dumps(["Accurate concepts", "Clear explanations"]),
            "weaknesses": json.dumps(["Add examples", "Explain trade-offs"]),
            "feedback": "Strong fundamentals; add concise examples to deepen future answers.",
        }

        with (
            patch(
                "groq_client.generate_question",
                side_effect=[*questions, {
                    "topic_area": "http caching",
                    "question": "What does HTTP caching do?",
                }],
            ),
            patch(
                "routes.answers.groq_client.evaluate_answer",
                return_value=answer_evaluation,
            ),
            patch(
                "routes.interviews.groq_client.evaluate_interview",
                return_value=final_evaluation.copy(),
            ),
        ):
            start = self.client.post(
                "/api/start_interview",
                json={
                    "student_id": 1,
                    "round_type": "technical",
                    "subject": "Python",
                    "difficulty": "beginner",
                    "num_questions": 5,
                },
            )
            self.assertEqual(start.status_code, 200, start.get_json())
            interview_id = start.get_json()["interview_id"]

            # Four distinct, idempotent focus-loss episodes cross the approved
            # event-count threshold without slowing the test for sixty seconds.
            for event_number in range(1, 5):
                event_uuid = f"00000000-0000-4000-8000-{event_number:012d}"
                left = self.client.post(
                    f"/api/interviews/{interview_id}/focus-events",
                    json={
                        "event_uuid": event_uuid,
                        "action": "left",
                        "source": "visibility",
                    },
                )
                returned = self.client.post(
                    f"/api/interviews/{interview_id}/focus-events",
                    json={
                        "event_uuid": event_uuid,
                        "action": "returned",
                        "source": "visibility",
                    },
                )
                self.assertEqual(left.status_code, 200, left.get_json())
                self.assertEqual(returned.status_code, 200, returned.get_json())

            for order in range(1, 6):
                submitted = self.client.post(
                    "/api/submit_answer",
                    json={
                        "interview_id": interview_id,
                        "question_order": order,
                        "answer": f"Integration answer {order}",
                        "time_taken_sec": 10 + order,
                    },
                )
                self.assertEqual(submitted.status_code, 200, submitted.get_json())
                self.assertEqual(submitted.get_json()["done"], order == 5)

            completed = self.client.post(
                "/api/end_interview", json={"interview_id": interview_id}
            )
            self.assertEqual(completed.status_code, 200, completed.get_json())
            self.assertEqual(completed.get_json()["overall_score"], 8.4)
            self.assertEqual(completed.get_json()["focus_loss_count"], 4)
            self.assertTrue(completed.get_json()["integrity_flagged"])

            exited_start = self.client.post(
                "/api/start_interview",
                json={
                    "student_id": 1,
                    "round_type": "technical",
                    "subject": "HTTP",
                    "difficulty": "beginner",
                    "num_questions": 5,
                },
            )
            self.assertEqual(exited_start.status_code, 200, exited_start.get_json())
            exited_id = exited_start.get_json()["interview_id"]
            exited = self.client.post(
                "/api/exit_interview", json={"interview_id": exited_id}
            )
            self.assertEqual(exited.status_code, 200, exited.get_json())
            self.assertEqual(exited.get_json()["status"], "exited")

        # Seed additional completed records in the disposable database so page
        # two is verified against real MySQL LIMIT/OFFSET and JOIN/GROUP BY.
        for index in range(4):
            _, seeded_id = db.query(
                """INSERT INTO interviews
                     (student_id, round_type, subject, difficulty, num_questions,
                      status, overall_score, technical_accuracy,
                      communication_clarity, confidence, ended_at)
                   VALUES (1, 'technical', %s, 'beginner', 5, 'completed',
                           %s, %s, %s, %s, NOW())""",
                (f"Seed {index}", 6.0 + index, 6.0 + index, 6.0 + index, 6.0 + index),
            )
            db.query(
                """INSERT INTO interview_details
                     (interview_id, question_order, question, is_followup,
                      answer, verdict, verdict_reason, processing_status)
                   VALUES (%s, 1, 'Seed question', FALSE, 'Seed answer',
                           'correct', 'Seed verdict', 'evaluated')""",
                (seeded_id,),
            )

        dashboard_cache.invalidate(1)
        dashboard = self.client.get("/api/dashboard/1")
        history = self.client.get("/api/history/1?page=2&limit=2")
        profile = self.client.get("/api/profile/1")

        self.assertEqual(dashboard.status_code, 200, dashboard.get_json())
        self.assertEqual(dashboard.get_json()["total_interviews"], 5)
        self.assertEqual(history.status_code, 200, history.get_json())
        self.assertEqual(history.get_json()["pagination"]["total_items"], 5)
        self.assertEqual(history.get_json()["pagination"]["page"], 2)
        self.assertEqual(len(history.get_json()["items"]), 2)
        self.assertTrue(all(item["total_questions"] == 1 for item in history.get_json()["items"]))
        self.assertEqual(profile.status_code, 200, profile.get_json())
        self.assertEqual(profile.get_json()["total_interviews"], 5)

        completed_row, _ = db.query(
            "SELECT status FROM interviews WHERE id = %s",
            (interview_id,),
            fetchone=True,
        )
        persisted_topics, _ = db.query(
            """SELECT topic_area
               FROM interview_details
               WHERE interview_id = %s AND is_followup = FALSE
               ORDER BY question_order""",
            (interview_id,),
            fetch=True,
        )
        exited_row, _ = db.query(
            "SELECT status FROM interviews WHERE id = %s",
            (exited_id,),
            fetchone=True,
        )
        self.assertEqual(completed_row["status"], "completed")
        self.assertEqual(exited_row["status"], "exited")
        self.assertEqual(
            [row["topic_area"] for row in persisted_topics],
            [item["topic_area"] for item in questions],
        )


if __name__ == "__main__":
    unittest.main()
