import { INTERVIEW_ICONS } from "../../utils/icons";
import VerdictBadge from "../ui/VerdictBadge";

const MicrophoneIcon = INTERVIEW_ICONS.microphone;

export default function CandidateAnswerPanel(props) {
  const { isListening, isCandidateSpeaking, voiceState, voiceStateLabel, phase, isTranscribing, manualAnswerMode, timeLeft, manualAnswerReason, manualAnswer, handleManualAnswerChange, submitManualAnswer, transcript, audioUrl, lastVerdict } = props;
  return <section className="interview-panel candidate-panel"><div className="panel-title-row"><div className={`mic-orb ${isListening ? "mic-orb-active" : ""}`} aria-hidden="true"><MicrophoneIcon size={24} strokeWidth={2} /></div><div><p className="eyebrow">Candidate Answer</p><h3>{isCandidateSpeaking ? "Speaking detected" : isListening ? "Listening now" : voiceStateLabel}</h3></div></div><div className="mic-zone"><div className={`voice-wave ${isListening ? "voice-wave-active" : ""}`} aria-hidden="true"><span /><span /><span /><span /><span /></div><p className={`voice-state voice-state-${voiceState}`} aria-live="polite">{voiceStateLabel}</p></div>{(phase === "submitting" || phase === "finishing") && <div className="processing-notice" role="status" aria-live="polite"><span className="processing-spinner" aria-hidden="true" /><span>{phase === "finishing" ? "Generating your interview results…" : isTranscribing ? "Transcribing and preparing your answer…" : "Answer received. Evaluating it now…"}</span></div>}{manualAnswerMode ? <div className="transcript-box transcript-live manual-answer-fallback"><div className="transcript-header"><label htmlFor="manual-interview-answer">Type your answer</label><span>{timeLeft}s remaining</span></div><p id="manual-answer-reason" className="manual-answer-reason" role="status">{manualAnswerReason}</p><textarea id="manual-interview-answer" value={manualAnswer} onChange={handleManualAnswerChange} rows={7} maxLength={20000} placeholder="Enter your answer here..." aria-describedby="manual-answer-reason" autoFocus /><div className="manual-answer-actions"><span>{manualAnswer.length.toLocaleString()} / 20,000 characters</span><button type="button" className="primary-btn" onClick={submitManualAnswer} disabled={phase === "submitting" || phase === "finishing"}>Submit Answer</button></div></div> : <div className="transcript-box transcript-live"><div className="transcript-header"><label>Live transcript</label><span>{transcript ? "Say “I’m done” to submit" : "Waiting for speech"}</span></div><p>{transcript || "Your answer will appear here while you speak."}</p>{audioUrl && <audio controls src={audioUrl} />}</div>}{lastVerdict && <VerdictBadge verdict={lastVerdict.verdict} reason={lastVerdict.reason} />}</section>;
}
