import logging
import json
import os
from urllib.parse import urlparse

import httpx
from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import Response

from app import config
from app.auth.agent_signing import sign_headers
from app.auth.security import decode_access_token
from app.auth import service as auth_service
from app.registry import service as registry_service

logger = logging.getLogger("orchestrator.gateway")
router = APIRouter(prefix="/gateway", tags=["gateway"])

# Registration itself has no way to know an agent's endpoint is legitimate
# beyond the shared secret, and the `action: "health"` branch below is
# intentionally unauthenticated — so without this check, anyone who can
# register an agent (or tamper with one's registered endpoint) can make this
# gateway proxy a request to an arbitrary host on the internal network.
# Every real agent endpoint is a loopback service on this box or an internal
# hostname; nothing else should ever be reachable through here.
#
# The fallback below must list every agent's actual Compose service hostname
# (see docker-compose.yml / each agent's AGENT_PUBLIC_URL), not just
# "127.0.0.1,localhost" -- an env var that's unset or reset to a bare
# default silently 403s every agent except whichever ones a deploy script
# has separately patched in (see scripts/prepare-production-env.sh's
# job-agent-specific repair), which is exactly the class of bug that script
# had to work around after the fact. Keep this in sync with
# agents/orchestrator/.env.example's ALLOWED_AGENT_HOSTS.
ALLOWED_AGENT_HOSTS = {
    h.strip() for h in os.environ.get(
        "ALLOWED_AGENT_HOSTS",
        "capstone-agent,codeforge-agent,communication-agent,aptitude-agent,"
        "resume-builder-agent,certificate-agent,job-agent,mock-interview-agent,"
        "127.0.0.1,localhost",
    ).split(",") if h.strip()
}

# Used only as a fallback when an agent hasn't yet been upgraded to report
# its real per-call token usage via the X-Tokens-Used response header (see
# aptitude_agent's app/services/usage_service.py for the reference
# implementation). New accounts start with 50,000 (see app/models.py),
# topped up via Razorpay (app/billing/routes.py).
TOKEN_COST_PER_CALL = int(os.environ.get("TOKEN_COST_PER_CALL", "100"))

# Background bookkeeping/status calls the UI fires on its own -- opening
# Settings, refreshing an "online" indicator, listing a static catalog --
# not something the user actually asked for, and none of them invoke an
# LLM. Only genuine agent interactions get billed.
FREE_ACTIONS = {
    "ensure_session", "usage_summary", "list_courses", "list_languages",
    "ensure_profile", "get_thread_status", "getThreadStatus",
    # Job Agent actions are database/scraper operations and do not invoke an
    # LLM. Keeping them free avoids applying the legacy per-call fallback to
    # deterministic reads, uploads, moderation and ingestion controls.
    "get_profile", "update_profile", "upload_resume", "download_resume", "get_categories",
    "get_feed", "get_saved_jobs", "get_hidden_jobs", "job_action", "chat",
    "get_applications", "export_user_data", "delete_user_data",
    "admin_list_users",
    "admin_update_plan", "admin_list_sources", "admin_create_source",
    "admin_update_source_status", "admin_run_source", "admin_list_runs",
    "admin_list_jobs", "admin_create_job", "admin_update_job_status",
    "admin_bulk_update_job_status", "admin_list_categories",
    "admin_greenhouse_companies", "admin_greenhouse_summary",
    "admin_greenhouse_pending_companies", "admin_greenhouse_revalidate",
    "admin_greenhouse_sync", "admin_greenhouse_run", "admin_apify_status",
    "admin_apify_actors", "admin_apify_run", "admin_tn_coverage",
    "admin_get_automation", "admin_update_automation",
    # Aptitude and Mock Interview reads and bookkeeping. None of these calls
    # an LLM; an action that reports no tokens would otherwise be charged the
    # flat TOKEN_COST_PER_CALL, so opening a dashboard or answering a
    # question cost tokens. Actions that do call an LLM (create_test, hint,
    # results, start_interview, submit_answer, end_interview) stay billable.
    "dashboard", "history", "history_detail", "profile", "analytics",
    "mixed_test_config", "save_mixed_test_config", "daily_usage",
    "active_interview", "status", "download_report", "record_focus_event",
    # State changes with no LLM call: questions are served from the batch
    # generated by create_test, and answers are graded locally.
    "question", "answer", "skip", "abandon", "exit_interview",
}


@router.post("/agents/{agent_name}/invoke")
async def invoke_registered_agent(agent_name: str, request: Request) -> Response:
    """Forward JSON or multipart bodies only to a live registry endpoint."""
    agent = registry_service.resolve_healthy(agent_name)
    if agent is None:
        raise HTTPException(503, f"Agent {agent_name!r} is not registered or its heartbeat is stale.")

    host = urlparse(agent.endpoint).hostname
    if host not in ALLOWED_AGENT_HOSTS:
        logger.warning(
            "blocked gateway invoke to disallowed host: agent=%s endpoint=%s host=%s", agent_name, agent.endpoint, host
        )
        raise HTTPException(403, f"Registered endpoint for {agent_name!r} is not on an allowed host.")

    body = await request.body()
    envelope = None
    if request.headers.get("content-type", "").startswith("application/json"):
        try:
            envelope = json.loads(body)
        except (TypeError, ValueError):
            pass

    # Health polling carries no learner data and remains public. Every other
    # action must be tied to a valid DigiDARA login.
    is_health = isinstance(envelope, dict) and envelope.get("action") == "health"
    user_id = None
    user = None
    if not is_health:
        authorization = request.headers.get("authorization", "")
        if not authorization.startswith("Bearer "):
            raise HTTPException(401, "Missing bearer token.")
        user_id = decode_access_token(authorization[7:])
        # Resolve every authenticated request, including free actions. This
        # rejects deleted accounts and supplies the trusted platform admin
        # flag that Job Agent authorization requires.
        user = auth_service.get_by_id(user_id)
        if user is None:
            raise HTTPException(401, "This account no longer exists.")

    action_name = envelope.get("action") if isinstance(envelope, dict) else None
    # The Job Agent's only multipart action is its deterministic resume
    # upload. Multipart bodies are forwarded byte-for-byte, so they are not
    # decoded into `envelope` above; identify this narrowly by the registered
    # agent plus media type instead of trusting a client-supplied billing
    # override header/query parameter.
    is_job_resume_upload = agent_name == "job_agent" and request.headers.get("content-type", "").startswith("multipart/form-data")
    is_multipart = request.headers.get("content-type", "").startswith("multipart/form-data")
    is_free_action = action_name in FREE_ACTIONS or is_job_resume_upload
    is_billable = bool(user_id) and not is_free_action

    if is_billable:
        # Cheap pre-check only -- blocks starting a new request once a
        # balance has already run out. The real, accurate charge for this
        # specific request happens after the response comes back below.
        if user.token_balance <= 0:
            raise HTTPException(402, "Insufficient token balance. Please top up to continue.")

    headers: dict[str, str] = {}
    if content_type := request.headers.get("content-type"):
        headers["content-type"] = content_type
    if accept := request.headers.get("accept"):
        headers["accept"] = accept
    if user_id:
        # Derived from the verified platform JWT, never from the JSON payload.
        headers["x-digidara-user-id"] = user_id
        headers["x-digidara-is-admin"] = "true" if user and user.is_admin else "false"
        headers["x-digidara-token-balance"] = str(user.token_balance) if user else "0"

    if isinstance(envelope, dict):
        if envelope.get("action") == "ensure_session":
            payload = envelope.get("payload") if isinstance(envelope.get("payload"), dict) else {}
            # Identity bridges receive only server-verified profile fields;
            # browser-supplied identity values are never forwarded.
            payload.update({"user_id": user.id, "name": user.name, "email": user.email, "mobile": user.mobile or ""})
            envelope["payload"] = payload
            body = json.dumps(envelope).encode("utf-8")

    # Aptitude batch creation and mock-interview question planning/final
    # evaluation can outlast ordinary agent calls. Keep their larger budgets
    # scoped to the actions that actually do this work.
    timeout_seconds = (
        config.APTITUDE_CREATE_TEST_TIMEOUT_SECONDS
        if agent_name == "aptitude_agent" and action_name == "create_test"
        else config.MOCK_INTERVIEW_GENERATION_TIMEOUT_SECONDS
        if agent_name == "mock_interview_agent" and action_name in {"start_interview", "end_interview"}
        # The submission upload is multipart (no decoded action), and a new viva attempt writes ten questions.
        else config.CAPSTONE_LONG_ACTION_TIMEOUT_SECONDS
        if agent_name == "capstone_project_agent" and (is_multipart or action_name == "start_viva_attempt")
        else config.AGENT_CALL_TIMEOUT_SECONDS
    )
    # Sign last, over the final body and the exact identity headers set above,
    # so agents can trust x-digidara-user-id / x-digidara-is-admin.
    headers.update(sign_headers(
        agent.agent_name, "POST", agent.endpoint, body,
        headers.get("x-digidara-user-id"), headers.get("x-digidara-is-admin"),
    ))
    try:
        async with httpx.AsyncClient(timeout=timeout_seconds) as client:
            upstream = await client.post(agent.endpoint, content=body, headers=headers)
    except httpx.TimeoutException as exc:
        logger.exception("gateway call timed out: agent=%s action=%s endpoint=%s timeout_seconds=%s", agent_name, action_name, agent.endpoint, timeout_seconds)
        raise HTTPException(504, f"Agent {agent_name!r} did not complete {action_name!r} before the gateway timeout.") from exc
    except httpx.HTTPError as exc:
        logger.exception("gateway call failed: agent=%s endpoint=%s", agent_name, agent.endpoint)
        raise HTTPException(502, f"Registered agent {agent_name!r} could not be reached.") from exc

    if is_billable:
        real_tokens = None
        header_value = upstream.headers.get("x-tokens-used")
        if header_value is not None:
            try:
                parsed = int(header_value)
                if parsed > 0:
                    real_tokens = parsed
            except ValueError:
                pass
        # Real usage when the agent reports it; otherwise the flat fallback
        # rate, so billing still works for agents not yet upgraded.
        auth_service.settle_tokens(user_id, real_tokens if real_tokens is not None else TOKEN_COST_PER_CALL)
    elif user_id:
        # For actions in FREE_ACTIONS that dynamically report token usage when free quota is exceeded
        header_value = upstream.headers.get("x-tokens-used")
        if header_value is not None:
            try:
                parsed = int(header_value)
                if parsed > 0:
                    auth_service.settle_tokens(user_id, parsed)
            except ValueError:
                pass

    response_headers: dict[str, str] = {}
    if upstream_content_type := upstream.headers.get("content-type"):
        response_headers["content-type"] = upstream_content_type
    if disposition := upstream.headers.get("content-disposition"):
        response_headers["content-disposition"] = disposition
    return Response(content=upstream.content, status_code=upstream.status_code, headers=response_headers)
